// AUTO-GENERATED from website/js/drinks-data.js + reservation-catalog.js — do not hand-edit.
// Bilingual display names for stored enquiry items (add-ons + drinks), keyed by id.
// enquiry-email.ts uses this to render item names in the customer's language; the
// stored item.name (always name_en) is the fallback for unknown / legacy ids.
// SYNC MAP: regenerate when an add-on or drink is added/renamed.
export const ITEM_NAMES: Record<string, { bg: string; en: string }> = {
  "arch": { bg: "Декоративна арка с осветление", en: "Decorative arch + lights" },
  "babich": { bg: "Babich Marlborough Sauvignon Blanc", en: "Babich Marlborough Sauvignon Blanc" },
  "bar_stool": { bg: "Бар стол", en: "Bar stool" },
  "barbayani": { bg: "Барбаяни Зелен етикет 0.70л", en: "Barbayani Green Label 0.70L" },
  "benedo_spa": { bg: "San Benedetto газирана 0.5л", en: "San Benedetto sparkling 0.5L" },
  "booth2": { bg: "Фото будка 360° (2 часа)", en: "360° Photo Booth (2 hours)" },
  "booth4": { bg: "Фото будка 360° (4 часа)", en: "360° Photo Booth (4 hours)" },
  "candles_h": { bg: "Свещи в залата — 60 бр.", en: "Hall candles 60 pcs" },
  "candles_t": { bg: "Свещи на терасата — 50 бр.", en: "Terrace candles 50 pcs" },
  "carpet_l": { bg: "Червена пътека (8 бр.)", en: "Red carpet (8 pieces)" },
  "carpet_s": { bg: "Червена пътека (6 бр.)", en: "Red carpet (6 pieces)" },
  "cheval_cs": { bg: "Cheval Cabernet Sauvignon", en: "Cheval Cabernet Sauvignon" },
  "cheval_sb": { bg: "Cheval Sauvignon Blanc Катаржина", en: "Cheval Sauvignon Blanc Katarzyna" },
  "chiavari": { bg: "Стол „Шивари“", en: "Chiavari chair" },
  "chivas12": { bg: "Chivas Regal 12 год. 0.70л", en: "Chivas Regal 12 year 0.70L" },
  "chivas18": { bg: "Chivas Regal 18 год. 0.70л", en: "Chivas Regal 18 year 0.70L" },
  "clase_azul": { bg: "Clase Azul Plata Ultra Prem. 0.70л", en: "Clase Azul Plata Ultra Prem. 0.70L" },
  "cleaning": { bg: "Почистване зала", en: "Hall cleaning" },
  "cocktail_t": { bg: "Коктейлна маса Ø70", en: "Cocktail table Ø70" },
  "cola": { bg: "Coca-Cola 0.33л", en: "Coca-Cola 0.33L" },
  "cola0": { bg: "Coca-Cola Zero 0.33л", en: "Coca-Cola Zero 0.33L" },
  "conf_chair": { bg: "Конферентен стол", en: "Conference chair" },
  "corona": { bg: "Corona Extra 0.335л", en: "Corona Extra 0.335L" },
  "decoration": { bg: "Украса (персонализирана)", en: "Decoration (custom)" },
  "dj": { bg: "DJ за 5 часа", en: "DJ for 5 hours" },
  "dom": { bg: "Dom Pérignon 0.75л", en: "Dom Pérignon 0.75L" },
  "fanta": { bg: "Fanta Портокал 0.33л", en: "Fanta Orange 0.33L" },
  "flare_l": { bg: "Заря 300–340 сек.", en: "Sparkle fountain 300–340s" },
  "flare_s": { bg: "Заря 150–170 сек.", en: "Sparkle fountain 150–170s" },
  "flipchart": { bg: "Флипчарт", en: "Flipchart" },
  "fountain_l": { bg: "Светлинен фонтан 2600мм", en: "Light fountain 2600mm" },
  "fountain_s": { bg: "Светлинен фонтан 1300мм", en: "Light fountain 1300mm" },
  "glen12": { bg: "Glenfiddich 12YO Single Malt", en: "Glenfiddich 12YO Single Malt" },
  "glen15": { bg: "Glenfiddich 15YO Single Malt", en: "Glenfiddich 15YO Single Malt" },
  "glow_table": { bg: "Маса светеща RGB", en: "RGB glowing table" },
  "granini_a": { bg: "Granini Сок ябълка 1л", en: "Granini Apple Juice 1L" },
  "granini_o": { bg: "Granini Сок портокал 1л", en: "Granini Orange Juice 1L" },
  "grey_goose": { bg: "Grey Goose Vodka", en: "Grey Goose Vodka" },
  "heater": { bg: "Газова отоплителна гъба", en: "Gas patio heater" },
  "heater_tbl": { bg: "Газова отоплителна маса", en: "Gas heating table" },
  "heineken": { bg: "Heineken 0.33л", en: "Heineken 0.33L" },
  "hygiene": { bg: "Хигиенист за 5 часа", en: "Hygienist 5h" },
  "jager": { bg: "Jägermeister", en: "Jägermeister" },
  "jw_black": { bg: "Johnnie Walker Black Label", en: "Johnnie Walker Black Label" },
  "jw_blue": { bg: "Johnnie Walker Blue Label 0.70л", en: "Johnnie Walker Blue Label 0.70L" },
  "jw_gold": { bg: "Johnnie Walker Gold Reserve", en: "Johnnie Walker Gold Reserve" },
  "laverite": { bg: "La Vérité Cabernet Franc", en: "La Vérité Cabernet Franc" },
  "le_rose": { bg: "Le Rosé Katarzyna 0.75л", en: "Le Rosé Katarzyna 0.75L" },
  "le_rose_375": { bg: "Le Rosé Katarzyna Estate 0.75л", en: "Le Rosé Katarzyna Estate 0.75L" },
  "le_volte": { bg: "Tenuta dell'Ornellaia Le Volte 0.75л", en: "Tenuta dell'Ornellaia Le Volte 0.75L" },
  "led": { bg: "LED екран", en: "LED screen" },
  "merlot_cheval": { bg: "Merlot Cheval de Катаржина 0.75л", en: "Merlot Cheval de Katarzyna 0.75L" },
  "mic": { bg: "Микрофони — 3бр. + брошка", en: "Microphones set" },
  "minuty": { bg: "M Minuty Rosé Côtes de Provence", en: "M Minuty Rosé Côtes de Provence" },
  "miraval_jp": { bg: "Miraval Studio Jolie & Pitt Rosé 0.75л", en: "Miraval Studio Jolie & Pitt Rosé 0.75L" },
  "miraval_r": { bg: "Château Miraval Rosé 0.75л", en: "Château Miraval Rosé 0.75L" },
  "miraval_w": { bg: "Château Miraval STUDIO бяло", en: "Château Miraval Studio White" },
  "moet": { bg: "Moët & Chandon Brut", en: "Moët & Chandon Brut" },
  "numbers": { bg: "Светещи цифри", en: "Light-up numbers" },
  "panna25": { bg: "Aqua Panna 0.25л", en: "Aqua Panna 0.25L" },
  "panna50": { bg: "Aqua Panna 0.5л", en: "Aqua Panna 0.5L" },
  "panna75": { bg: "Aqua Panna 0.75л", en: "Aqua Panna 0.75L" },
  "patron": { bg: "Patrón Silver Tequila 0.70л", en: "Patrón Silver Tequila 0.70L" },
  "pelegrino": { bg: "San Pellegrino газирана 0.25л", en: "San Pellegrino sparkling 0.25L" },
  "pelegrino75": { bg: "San Pellegrino газирана 0.75л", en: "San Pellegrino sparkling 0.75L" },
  "perrier_spa": { bg: "Perrier Газирана минерална 0.33л", en: "Perrier Sparkling Mineral 0.33L" },
  "perrier_st": { bg: "Perrier Минерална вода 0.33л", en: "Perrier Mineral Water 0.33L" },
  "photo2": { bg: "Фотограф за 2 часа", en: "Photographer 2h" },
  "photo4": { bg: "Фотограф за 4 часа", en: "Photographer 4h" },
  "proj": { bg: "Мултимедия EPSON", en: "EPSON multimedia projector" },
  "prosecco": { bg: "Andreola Prosecco Dirupo 0.75л", en: "Andreola Prosecco Dirupo 0.75L" },
  "prosecco_glera": { bg: "Andreola Prosecco Glera Superiore DOCG 0.75л", en: "Andreola Prosecco Glera Superiore DOCG 0.75L" },
  "question_mark": { bg: "Question Mark Катаржина 2020 0.75л", en: "Question Mark Katarzyna 2020 0.75L" },
  "rect_table": { bg: "Правоъгълна маса 180", en: "Rectangular table 180" },
  "redbull": { bg: "Red Bull 0.355л", en: "Red Bull 0.355L" },
  "reyka": { bg: "Reyka Vodka 0.70л", en: "Reyka Vodka 0.70L" },
  "round_table": { bg: "Кръгла маса Ø152", en: "Round table Ø152" },
  "ruinart": { bg: "Ruinart Blanc de Blanc 0.75л", en: "Ruinart Blanc de Blanc 0.75L" },
  "russian_std": { bg: "Руски Стандарт Водка", en: "Russian Standard Vodka" },
  "sanben_tea_lem3": { bg: "San Benedetto Студен чай лимон 0.33л кен", en: "San Benedetto Iced Tea Lemon 0.33L can" },
  "sanben_tea_lem5": { bg: "San Benedetto Студен чай лимон 0.5л", en: "San Benedetto Iced Tea Lemon 0.5L" },
  "sanben_tea_peach": { bg: "San Benedetto Студен чай праскова 0.33л кен", en: "San Benedetto Iced Tea Peach 0.33L can" },
  "security": { bg: "Охрана VTA за 6 часа", en: "VTA security 6h" },
  "stclair": { bg: "Saint Clair Marlborough Sauv. Blanc", en: "Saint Clair Marlborough Sauv. Blanc" },
  "tonic_cherry": { bg: "Thomas Henry Cherry Blossom тоник", en: "Thomas Henry Cherry Blossom Tonic" },
  "tonic_mango": { bg: "Thomas Henry Mystic Mango тоник", en: "Thomas Henry Mystic Mango Tonic" },
  "uzo": { bg: "Узо Пломари", en: "Uzo Plomari" },
  "valet": { bg: "Вале-паркинг за 5 часа", en: "Valet parking 5h" },
  "veuve": { bg: "Veuve Clicquot Brut", en: "Veuve Clicquot Brut" },
  "villa": { bg: "Villa Maria Private Bin Sauv. Blanc", en: "Villa Maria Private Bin Sauv. Blanc" },
  "wall_g": { bg: "Декоративна стена GOLD", en: "Decorative wall GOLD" },
  "wall_s": { bg: "Декоративна стена SILVER", en: "Decorative wall SILVER" },
  "wardrobe": { bg: "Гардеробиер за 5 часа", en: "Wardrobe attendant 5h" },
};

export function localizedItemName(item: { id?: string | null; name?: string | null }, lang: "bg" | "en"): string {
  const entry = item && item.id ? ITEM_NAMES[item.id] : undefined;
  return entry ? entry[lang] : String((item && item.name) ?? (item && item.id) ?? "");
}
