// SEO/GEO content blocks - admin-managed text sections (public.content_blocks,
// editor at admin/content.html). Each included page carries a BAKED static
// copy of its blocks for non-JS crawlers (regenerated by
// scripts/bake-content-blocks.mjs); this script replaces it at runtime with
// the live DB rows so manager edits show without a deploy. Plain REST like
// catalog-db.js; on any failure the baked copy simply stays.
(function () {
  const SB_URL = 'https://wlxutsufrobzovdsiecb.supabase.co';
  const SB_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndseHV0c3Vmcm9iem92ZHNpZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MDc3MDQsImV4cCI6MjA5MTQ4MzcwNH0.EY2j3lZRmfGlWcTTNy9CMIHZX1E-2jit11jZwP7UOJo';

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  function pageKey() {
    const file = (location.pathname.split('/').pop() || '').replace(/\.html$/, '');
    return file || 'index';
  }

  function lang() {
    return document.documentElement.lang === 'en' ? 'en' : 'bg';
  }

  let blocks = null; // fetched rows for this page

  function render() {
    const section = document.getElementById('content-blocks-section');
    const holder = document.getElementById('content-blocks');
    if (!section || !holder || !blocks) return;
    if (!blocks.length) { section.hidden = true; return; }
    const L = lang();
    holder.innerHTML = blocks.map(function (b) {
      const title = L === 'en' ? b.title_en : b.title_bg;
      const body = L === 'en' ? b.body_en : b.body_bg;
      const paras = String(body || '').split(/\n\s*\n/)
        .map(function (p) { return p.trim(); })
        .filter(Boolean)
        .map(function (p) { return '<p>' + esc(p).replace(/\n/g, '<br>') + '</p>'; })
        .join('');
      return '<article class="content-block"><h2>' + esc(title) + '</h2>' + paras + '</article>';
    }).join('');
    section.hidden = false;
  }

  document.addEventListener('DOMContentLoaded', function () {
    if (!document.getElementById('content-blocks-section')) return;
    fetch(SB_URL + '/rest/v1/content_blocks' +
          '?select=title_bg,title_en,body_bg,body_en,sort_order' +
          '&active=is.true&page=eq.' + encodeURIComponent(pageKey()) +
          '&order=sort_order.asc',
          { headers: { apikey: SB_ANON, Authorization: 'Bearer ' + SB_ANON } })
      .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
      .then(function (rows) { blocks = rows; render(); })
      .catch(function (e) { console.warn('content blocks: keeping baked copy -', e); });

    // main.js flips <html lang> on the language toggle - re-render to match.
    new MutationObserver(render)
      .observe(document.documentElement, { attributes: true, attributeFilter: ['lang'] });
  });
})();
