// Shared drinks catalog used by both reservation.js (picker) and drinks.js (menu page)
const drinkCategories = {
  bg: ['Шампанско', 'Вино', 'Алкохол & Уиски', 'Безалкохолно', 'Вода'],
  en: ['Champagne', 'Wine', 'Spirits & Whisky', 'Soft Drinks', 'Water'],
};

const drinks = [
  // Champagne & Sparkling
  { id:'dom',            cat:0, name_bg:'Dom Pérignon 0.75л',                    name_en:'Dom Pérignon 0.75L',                 price_eur:361.99, img:'assets/images/drinks/dom-perignon.png' },
  { id:'ruinart',        cat:0, name_bg:'Ruinart Blanc de Blanc 0.75л',          name_en:'Ruinart Blanc de Blanc 0.75L',       price_eur:122.71, img:'assets/images/drinks/ruinart.png' },
  { id:'veuve',          cat:0, name_bg:'Veuve Clicquot Brut',                   name_en:'Veuve Clicquot Brut',                price_eur:70.56,  img:'assets/images/drinks/veuve-clicquot.png' },
  { id:'moet',           cat:0, name_bg:'Moët & Chandon Brut',                   name_en:'Moët & Chandon Brut',                price_eur:62.38,  img:'assets/images/drinks/moet.png' },
  { id:'prosecco',       cat:0, name_bg:'Andreola Prosecco Dirupo 0.75л',        name_en:'Andreola Prosecco Dirupo 0.75L',     price_eur:15.85,  img:'assets/images/drinks/prosecco.png' },
  { id:'prosecco_glera', cat:0, name_bg:'Andreola Prosecco Glera Superiore DOCG 0.75л', name_en:'Andreola Prosecco Glera Superiore DOCG 0.75L', price_eur:18.81, img:'assets/images/drinks/prosecco-glera.png' },
  // Wine — Red, White, Rosé
  { id:'le_volte',       cat:1, name_bg:"Tenuta dell'Ornellaia Le Volte 0.75л",  name_en:"Tenuta dell'Ornellaia Le Volte 0.75L", price_eur:30.17, img:'assets/images/drinks/le-volte.png' },
  { id:'laverite',       cat:1, name_bg:'La Vérité Cabernet Franc',              name_en:'La Vérité Cabernet Franc',           price_eur:21.99,  img:'assets/images/drinks/laverite-cabernet-franc.png' },
  { id:'question_mark',  cat:1, name_bg:'Question Mark Катаржина 2020 0.75л',    name_en:'Question Mark Katarzyna 2020 0.75L', price_eur:17.36, img:'assets/images/drinks/question-mark-katarzyna.png' },
  { id:'merlot_cheval',  cat:1, name_bg:'Merlot Cheval de Катаржина 0.75л',      name_en:'Merlot Cheval de Katarzyna 0.75L',   price_eur:7.67,   img:'assets/images/drinks/merlot-cheval.png' },
  { id:'cheval_cs',      cat:1, name_bg:'Cheval Cabernet Sauvignon',             name_en:'Cheval Cabernet Sauvignon',          price_eur:7.67,   img:'assets/images/drinks/cheval-cabernet-sauvignon.png' },
  { id:'miraval_w',      cat:1, name_bg:'Château Miraval STUDIO бяло',           name_en:'Château Miraval Studio White',       price_eur:22.50,  img:'assets/images/drinks/miraval-white.png' },
  { id:'villa',          cat:1, name_bg:'Villa Maria Private Bin Sauv. Blanc',   name_en:'Villa Maria Private Bin Sauv. Blanc',price_eur:17.38,  img:'assets/images/drinks/sauvignon-villa.png' },
  { id:'babich',         cat:1, name_bg:'Babich Marlborough Sauvignon Blanc',    name_en:'Babich Marlborough Sauvignon Blanc', price_eur:15.85,  img:'assets/images/drinks/babich-marlborough.png' },
  { id:'stclair',        cat:1, name_bg:'Saint Clair Marlborough Sauv. Blanc',   name_en:'Saint Clair Marlborough Sauv. Blanc',price_eur:13.80,  img:'assets/images/drinks/saintclair-marlborough.png' },
  { id:'cheval_sb',      cat:1, name_bg:'Cheval Sauvignon Blanc Катаржина',      name_en:'Cheval Sauvignon Blanc Katarzyna',   price_eur:7.67,   img:'assets/images/drinks/cheval-sauvignon-blanc.png' },
  { id:'miraval_jp',     cat:1, name_bg:'Miraval Studio Jolie & Pitt Rosé 0.75л',name_en:'Miraval Studio Jolie & Pitt Rosé 0.75L', price_eur:34.77, img:'assets/images/drinks/miraval-jolie-pitt-rose.png' },
  { id:'minuty',         cat:1, name_bg:'M Minuty Rosé Côtes de Provence',       name_en:'M Minuty Rosé Côtes de Provence',    price_eur:22.50,  img:'assets/images/drinks/minuty-rose.png' },
  { id:'miraval_r',      cat:1, name_bg:'Château Miraval Rosé 0.75л',            name_en:'Château Miraval Rosé 0.75L',         price_eur:35.79,  img:'assets/images/drinks/miraval-rose.png' },
  { id:'le_rose',        cat:1, name_bg:'Le Rosé Katarzyna 0.75л',               name_en:'Le Rosé Katarzyna 0.75L',            price_eur:13.29,  img:'assets/images/drinks/le-rose.png' },
  { id:'le_rose_375',    cat:1, name_bg:'Le Rosé Katarzyna Estate 0.375л',       name_en:'Le Rosé Katarzyna Estate 0.375L',    price_eur:5.16,   img:'assets/images/drinks/le-rose-375.png' },
  // Spirits & Whisky (incl. beer + vodka + tequila + liqueurs)
  { id:'heineken',       cat:2, name_bg:'Heineken 0.33л',                        name_en:'Heineken 0.33L',                     price_eur:1.18,   img:'assets/images/drinks/heineken.png' },
  { id:'corona',         cat:2, name_bg:'Corona Extra 0.335л',                   name_en:'Corona Extra 0.335L',                price_eur:1.69,   img:'assets/images/drinks/corona-extra.png' },
  { id:'jager',          cat:2, name_bg:'Jägermeister',                          name_en:'Jägermeister',                       price_eur:12.78,  img:'assets/images/drinks/jagermeister.png' },
  { id:'uzo',            cat:2, name_bg:'Узо Пломари',                           name_en:'Uzo Plomari',                        price_eur:4.60,   img:'assets/images/drinks/uzo.png' },
  { id:'barbayani',      cat:2, name_bg:'Барбаяни Зелен етикет 0.70л',           name_en:'Barbayani Green Label 0.70L',        price_eur:15.34,  img:'assets/images/drinks/barbayani.png' },
  { id:'patron',         cat:2, name_bg:'Patrón Silver Tequila 0.70л',           name_en:'Patrón Silver Tequila 0.70L',        price_eur:64.42,  img:'assets/images/drinks/patron.png' },
  { id:'clase_azul',     cat:2, name_bg:'Clase Azul Plata Ultra Prem. 0.70л',    name_en:'Clase Azul Plata Ultra Prem. 0.70L', price_eur:139.58, img:'assets/images/drinks/clase-azul-plata.png' },
  { id:'jw_blue',        cat:2, name_bg:'Johnnie Walker Blue Label 0.70л',       name_en:'Johnnie Walker Blue Label 0.70L',    price_eur:277.12, img:'assets/images/drinks/johnnie-walker-blue.png' },
  { id:'chivas18',       cat:2, name_bg:'Chivas Regal 18 год. 0.70л',            name_en:'Chivas Regal 18 year 0.70L',         price_eur:75.16,  img:'assets/images/drinks/chivas18.png' },
  { id:'chivas12',       cat:2, name_bg:'Chivas Regal 12 год. 0.70л',            name_en:'Chivas Regal 12 year 0.70L',         price_eur:29.65,  img:'assets/images/drinks/chivas12.png' },
  { id:'glen15',         cat:2, name_bg:'Glenfiddich 15YO Single Malt',          name_en:'Glenfiddich 15YO Single Malt',       price_eur:61.36,  img:'assets/images/drinks/glenfiddich-15.png' },
  { id:'glen12',         cat:2, name_bg:'Glenfiddich 12YO Single Malt',          name_en:'Glenfiddich 12YO Single Malt',       price_eur:44.99,  img:'assets/images/drinks/glenfiddich-12.png' },
  { id:'jw_gold',        cat:2, name_bg:'Johnnie Walker Gold Reserve',           name_en:'Johnnie Walker Gold Reserve',        price_eur:53.17,  img:'assets/images/drinks/johnnie-walker-gold.png' },
  { id:'jw_black',       cat:2, name_bg:'Johnnie Walker Black Label',            name_en:'Johnnie Walker Black Label',         price_eur:29.65,  img:'assets/images/drinks/johnnie-walker-black.png' },
  { id:'grey_goose',     cat:2, name_bg:'Grey Goose Vodka',                      name_en:'Grey Goose Vodka',                   price_eur:47.04,  img:'assets/images/drinks/grey-goose.png' },
  { id:'goose_cherry',   cat:2, name_bg:'Grey Goose Cherry 1л',                  name_en:'Grey Goose Cherry 1L',               price_eur:48.57,  img:'assets/images/drinks/grey-goose-cherry.png' },
  { id:'goose_watermelon',cat:2,name_bg:'Grey Goose Диня и Босилек 1л',          name_en:'Grey Goose Watermelon & Basil 1L',   price_eur:56.24,  img:'assets/images/drinks/grey-goose-watermelon.png' },
  { id:'reyka',          cat:2, name_bg:'Reyka Vodka 0.70л',                     name_en:'Reyka Vodka 0.70L',                  price_eur:24.03,  img:'assets/images/drinks/reyka.png' },
  { id:'russian_std',    cat:2, name_bg:'Руски Стандарт Водка',                  name_en:'Russian Standard Vodka',             price_eur:12.78,  img:'assets/images/drinks/russian-standard.png' },
  // Soft Drinks (juices, tonics, colas, energy)
  { id:'granini_a',      cat:3, name_bg:'Granini Сок ябълка 1л',                 name_en:'Granini Apple Juice 1L',             price_eur:2.25,   img:'assets/images/drinks/granini-apple.png' },
  { id:'granini_o',      cat:3, name_bg:'Granini Сок портокал 1л',               name_en:'Granini Orange Juice 1L',            price_eur:2.25,   img:'assets/images/drinks/granini-orange.png' },
  { id:'tonic_mango',    cat:3, name_bg:'Thomas Henry Mystic Mango тоник',       name_en:'Thomas Henry Mystic Mango Tonic',    price_eur:1.99,   img:'assets/images/drinks/tonic-mango.png' },
  { id:'tonic_cherry',   cat:3, name_bg:'Thomas Henry Cherry Blossom тоник',     name_en:'Thomas Henry Cherry Blossom Tonic',  price_eur:1.99,   img:'assets/images/drinks/tonic-cherry.png' },
  { id:'sanben_tea_lem5',cat:3, name_bg:'San Benedetto Студен чай лимон 0.5л',   name_en:'San Benedetto Iced Tea Lemon 0.5L',  price_eur:0.72,   img:'assets/images/drinks/sanben-tea-lemon-500.png' },
  { id:'sanben_tea_lem3',cat:3, name_bg:'San Benedetto Студен чай лимон 0.33л кен', name_en:'San Benedetto Iced Tea Lemon 0.33L can', price_eur:1.07, img:'assets/images/drinks/sanben-tea-lemon-330.png' },
  { id:'sanben_tea_peach',cat:3,name_bg:'San Benedetto Студен чай праскова 0.33л кен', name_en:'San Benedetto Iced Tea Peach 0.33L can', price_eur:1.07, img:'assets/images/drinks/sanben-tea-peach-330.png' },
  { id:'cola',           cat:3, name_bg:'Coca-Cola 0.33л',                       name_en:'Coca-Cola 0.33L',                    price_eur:1.07,   img:'assets/images/drinks/coca-cola.png' },
  { id:'cola0',          cat:3, name_bg:'Coca-Cola Zero 0.33л',                  name_en:'Coca-Cola Zero 0.33L',               price_eur:1.07,   img:'assets/images/drinks/coca-zero.png' },
  { id:'fanta',          cat:3, name_bg:'Fanta Портокал 0.33л',                  name_en:'Fanta Orange 0.33L',                 price_eur:1.07,   img:'assets/images/drinks/fanta.png' },
  { id:'redbull',        cat:3, name_bg:'Red Bull 0.355л',                       name_en:'Red Bull 0.355L',                    price_eur:1.59,   img:'assets/images/drinks/red-bull.png' },
  // Water
  { id:'devin',          cat:4, name_bg:'Devin Минерална вода 0.4л',             name_en:'Devin Mineral Water 0.4L',           price_eur:0.36,   img:'assets/images/drinks/devin.png' },
  { id:'benedo_st',      cat:4, name_bg:'San Benedetto минерална 0.5л',          name_en:'San Benedetto still 0.5L',           price_eur:0.82,   img:'assets/images/drinks/san-benedetto-still.png' },
  { id:'benedo_spa',     cat:4, name_bg:'San Benedetto газирана 0.5л',           name_en:'San Benedetto sparkling 0.5L',       price_eur:0.82,   img:'assets/images/drinks/san-benedetto-sparkling.png' },
  { id:'perrier_st',     cat:4, name_bg:'Perrier Минерална вода 0.33л',          name_en:'Perrier Mineral Water 0.33L',        price_eur:1.23,   img:'assets/images/drinks/perrier-still.png' },
  { id:'perrier_spa',    cat:4, name_bg:'Perrier Газирана минерална 0.33л',      name_en:'Perrier Sparkling Mineral 0.33L',    price_eur:1.64,   img:'assets/images/drinks/perrier-sparkling.png' },
  { id:'panna25',        cat:4, name_bg:'Aqua Panna 0.25л',                      name_en:'Aqua Panna 0.25L',                   price_eur:1.53,   img:'assets/images/drinks/aqua-panna-25.png' },
  { id:'panna75',        cat:4, name_bg:'Aqua Panna 0.75л',                      name_en:'Aqua Panna 0.75L',                   price_eur:2.56,   img:'assets/images/drinks/aqua-panna-75.png' },
  { id:'pelegrino75',    cat:4, name_bg:'San Pellegrino газирана 0.75л',         name_en:'San Pellegrino sparkling 0.75L',     price_eur:2.86,   img:'assets/images/drinks/san-pelegrino-75.png' },
  { id:'pelegrino',      cat:4, name_bg:'San Pellegrino газирана 0.25л',         name_en:'San Pellegrino sparkling 0.25L',     price_eur:1.53,   img:'assets/images/drinks/san-pelegrino.png' },
];
