-- Drinks + addon-services catalog, editable from the admin panel
-- (admin/catalog.html). Single source of truth for items and prices:
-- the public site fetches these tables via anon REST (same model as
-- partners) and the enquiry edge functions reprice every item from them.
-- The static drinks-data.js / addonServices arrays are removed in the
-- follow-up code change (PR feat/catalog-switch).

CREATE TABLE IF NOT EXISTS public.drinks (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  cat smallint NOT NULL CHECK (cat BETWEEN 0 AND 4),
  name_bg text NOT NULL,
  name_en text NOT NULL,
  price_eur numeric(8,2) NOT NULL CHECK (price_eur >= 0),
  img text,
  active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.addon_services (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name_bg text NOT NULL,
  name_en text NOT NULL,
  price_eur numeric(8,2) NOT NULL CHECK (price_eur >= 0),
  hint_bg text,
  hint_en text,
  free_until int CHECK (free_until IS NULL OR free_until >= 0),
  max_qty int CHECK (max_qty IS NULL OR max_qty >= 1),
  img text,
  active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.drinks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addon_services ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS drinks_public_read ON public.drinks;
CREATE POLICY drinks_public_read ON public.drinks
  FOR SELECT TO anon USING (active);

DROP POLICY IF EXISTS drinks_admin_all ON public.drinks;
CREATE POLICY drinks_admin_all ON public.drinks
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

DROP POLICY IF EXISTS addon_services_public_read ON public.addon_services;
CREATE POLICY addon_services_public_read ON public.addon_services
  FOR SELECT TO anon USING (active);

DROP POLICY IF EXISTS addon_services_admin_all ON public.addon_services;
CREATE POLICY addon_services_admin_all ON public.addon_services
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- The mandatory cleaning addon (id 'cleaning') is auto-added to every event
-- by the wizard and the customer edit page (autoCleaningAddon) and has a
-- dedicated always-on row in the offer XLSX (AA85). Deleting or hiding it
-- would break both, so the DB refuses; its price stays editable.
CREATE OR REPLACE FUNCTION public.protect_cleaning_addon() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.id = 'cleaning' THEN
      RAISE EXCEPTION 'the cleaning addon cannot be deleted';
    END IF;
    RETURN OLD;
  END IF;
  IF OLD.id = 'cleaning' AND (NEW.id IS DISTINCT FROM 'cleaning' OR NEW.active = false) THEN
    RAISE EXCEPTION 'the cleaning addon cannot be hidden or re-keyed';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS addon_services_protect_cleaning ON public.addon_services;
CREATE TRIGGER addon_services_protect_cleaning
  BEFORE UPDATE OR DELETE ON public.addon_services
  FOR EACH ROW EXECUTE FUNCTION public.protect_cleaning_addon();

-- Storage bucket for catalog item images (same policy shape as
-- partner-images). Seeded rows keep their repo asset paths ('assets/…');
-- only newly uploaded images live in this bucket.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('catalog-images', 'catalog-images', true, 5242880,
        ARRAY['image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS catalog_images_admin_insert ON storage.objects;
CREATE POLICY catalog_images_admin_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'catalog-images' AND is_admin());

DROP POLICY IF EXISTS catalog_images_admin_update ON storage.objects;
CREATE POLICY catalog_images_admin_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'catalog-images' AND is_admin())
  WITH CHECK (bucket_id = 'catalog-images' AND is_admin());

DROP POLICY IF EXISTS catalog_images_admin_delete ON storage.objects;
CREATE POLICY catalog_images_admin_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'catalog-images' AND is_admin());

-- ── Seed (generated by scratchpad/gen-catalog-seed.mjs) ──────────────

-- Seed: drinks (generated from website/js/drinks-data.js, verbatim)
INSERT INTO public.drinks (id, cat, name_bg, name_en, price_eur, img, sort_order) VALUES
  ('dom', 0, 'Dom Pérignon 0.75л', 'Dom Pérignon 0.75L', 320.58, 'assets/images/drinks/dom-perignon.png', 10),
  ('ruinart', 0, 'Ruinart Blanc de Blanc 0.75л', 'Ruinart Blanc de Blanc 0.75L', 122.71, 'assets/images/drinks/ruinart.png', 20),
  ('veuve', 0, 'Veuve Clicquot Brut', 'Veuve Clicquot Brut', 70.56, 'assets/images/drinks/veuve-clicquot.png', 30),
  ('moet', 0, 'Moët & Chandon Brut', 'Moët & Chandon Brut', 62.38, 'assets/images/drinks/moet.png', 40),
  ('prosecco', 0, 'Andreola Prosecco Dirupo 0.75л', 'Andreola Prosecco Dirupo 0.75L', 15.85, 'assets/images/drinks/prosecco.png', 50),
  ('prosecco_glera', 0, 'Andreola Prosecco Glera Superiore DOCG 0.75л', 'Andreola Prosecco Glera Superiore DOCG 0.75L', 18.81, 'assets/images/drinks/prosecco-glera.png', 60),
  ('le_volte', 1, 'Tenuta dell''Ornellaia Le Volte 0.75л', 'Tenuta dell''Ornellaia Le Volte 0.75L', 30.17, 'assets/images/drinks/le-volte.png', 10),
  ('laverite', 1, 'La Vérité Cabernet Franc', 'La Vérité Cabernet Franc', 21.99, 'assets/images/drinks/laverite-cabernet-franc.png', 20),
  ('question_mark', 1, 'Question Mark Катаржина 2020 0.75л', 'Question Mark Katarzyna 2020 0.75L', 17.36, 'assets/images/drinks/question-mark-katarzyna.png', 30),
  ('merlot_cheval', 1, 'Merlot Cheval de Катаржина 0.75л', 'Merlot Cheval de Katarzyna 0.75L', 7.67, 'assets/images/drinks/merlot-cheval.png', 40),
  ('cheval_cs', 1, 'Cheval Cabernet Sauvignon', 'Cheval Cabernet Sauvignon', 7.67, 'assets/images/drinks/cheval-cabernet-sauvignon.png', 50),
  ('miraval_w', 1, 'Château Miraval STUDIO бяло', 'Château Miraval Studio White', 22.5, 'assets/images/drinks/miraval-white.png', 60),
  ('villa', 1, 'Villa Maria Private Bin Sauv. Blanc', 'Villa Maria Private Bin Sauv. Blanc', 17.38, 'assets/images/drinks/sauvignon-villa.png', 70),
  ('babich', 1, 'Babich Marlborough Sauvignon Blanc', 'Babich Marlborough Sauvignon Blanc', 15.85, 'assets/images/drinks/babich-marlborough.png', 80),
  ('stclair', 1, 'Saint Clair Marlborough Sauv. Blanc', 'Saint Clair Marlborough Sauv. Blanc', 13.8, 'assets/images/drinks/saintclair-marlborough.png', 90),
  ('cheval_sb', 1, 'Cheval Sauvignon Blanc Катаржина', 'Cheval Sauvignon Blanc Katarzyna', 7.67, 'assets/images/drinks/cheval-sauvignon-blanc.png', 100),
  ('miraval_jp', 1, 'Miraval Studio Jolie & Pitt Rosé 0.75л', 'Miraval Studio Jolie & Pitt Rosé 0.75L', 34.77, 'assets/images/drinks/miraval-jolie-pitt-rose.png', 110),
  ('minuty', 1, 'M Minuty Rosé Côtes de Provence', 'M Minuty Rosé Côtes de Provence', 22.5, 'assets/images/drinks/minuty-rose.png', 120),
  ('miraval_r', 1, 'Château Miraval Rosé 0.75л', 'Château Miraval Rosé 0.75L', 34.77, 'assets/images/drinks/miraval-rose.png', 130),
  ('le_rose', 1, 'Le Rosé Katarzyna 0.75л', 'Le Rosé Katarzyna 0.75L', 13.29, 'assets/images/drinks/le-rose-375.png', 140),
  ('le_rose_375', 1, 'Le Rosé Katarzyna Estate 0.75л', 'Le Rosé Katarzyna Estate 0.75L', 13.29, 'assets/images/drinks/le-rose-375.png', 150),
  ('heineken', 2, 'Heineken 0.33л', 'Heineken 0.33L', 1.18, 'assets/images/drinks/heineken.png', 10),
  ('corona', 2, 'Corona Extra 0.335л', 'Corona Extra 0.335L', 1.69, 'assets/images/drinks/corona-extra.png', 20),
  ('jager', 2, 'Jägermeister', 'Jägermeister', 12.78, 'assets/images/drinks/jagermeister.png', 30),
  ('uzo', 2, 'Узо Пломари', 'Uzo Plomari', 4.6, 'assets/images/drinks/uzo.png', 40),
  ('barbayani', 2, 'Барбаяни Зелен етикет 0.70л', 'Barbayani Green Label 0.70L', 15.34, 'assets/images/drinks/barbayani.png', 50),
  ('patron', 2, 'Patrón Silver Tequila 0.70л', 'Patrón Silver Tequila 0.70L', 64.42, 'assets/images/drinks/patron.png', 60),
  ('clase_azul', 2, 'Clase Azul Plata Ultra Prem. 0.70л', 'Clase Azul Plata Ultra Prem. 0.70L', 139.58, 'assets/images/drinks/clase-azul-plata.png', 70),
  ('jw_blue', 2, 'Johnnie Walker Blue Label 0.70л', 'Johnnie Walker Blue Label 0.70L', 277.12, 'assets/images/drinks/johnnie-walker-blue.png', 80),
  ('chivas18', 2, 'Chivas Regal 18 год. 0.70л', 'Chivas Regal 18 year 0.70L', 75.16, 'assets/images/drinks/chivas18.png', 90),
  ('chivas12', 2, 'Chivas Regal 12 год. 0.70л', 'Chivas Regal 12 year 0.70L', 29.65, 'assets/images/drinks/chivas12.png', 100),
  ('glen15', 2, 'Glenfiddich 15YO Single Malt', 'Glenfiddich 15YO Single Malt', 61.36, 'assets/images/drinks/glenfiddich-15.png', 110),
  ('glen12', 2, 'Glenfiddich 12YO Single Malt', 'Glenfiddich 12YO Single Malt', 44.99, 'assets/images/drinks/glenfiddich-12.png', 120),
  ('jw_gold', 2, 'Johnnie Walker Gold Reserve', 'Johnnie Walker Gold Reserve', 53.17, 'assets/images/drinks/johnnie-walker-gold.png', 130),
  ('jw_black', 2, 'Johnnie Walker Black Label', 'Johnnie Walker Black Label', 29.65, 'assets/images/drinks/johnnie-walker-black.png', 140),
  ('grey_goose', 2, 'Grey Goose Vodka', 'Grey Goose Vodka', 47.04, 'assets/images/drinks/grey-goose.png', 150),
  ('reyka', 2, 'Reyka Vodka 0.70л', 'Reyka Vodka 0.70L', 24.03, 'assets/images/drinks/reyka.png', 160),
  ('russian_std', 2, 'Руски Стандарт Водка', 'Russian Standard Vodka', 12.78, 'assets/images/drinks/russian-standard.png', 170),
  ('granini_a', 3, 'Granini Сок ябълка 1л', 'Granini Apple Juice 1L', 2.25, 'assets/images/drinks/granini-apple.png', 10),
  ('granini_o', 3, 'Granini Сок портокал 1л', 'Granini Orange Juice 1L', 2.25, 'assets/images/drinks/granini-orange.png', 20),
  ('tonic_mango', 3, 'Thomas Henry Mystic Mango тоник', 'Thomas Henry Mystic Mango Tonic', 1.99, 'assets/images/drinks/tonic-mango.png', 30),
  ('tonic_cherry', 3, 'Thomas Henry Cherry Blossom тоник', 'Thomas Henry Cherry Blossom Tonic', 1.99, 'assets/images/drinks/tonic-cherry.png', 40),
  ('sanben_tea_lem5', 3, 'San Benedetto Студен чай лимон 0.5л', 'San Benedetto Iced Tea Lemon 0.5L', 0.72, 'assets/images/drinks/sanben-tea-lemon-500.png', 50),
  ('sanben_tea_lem3', 3, 'San Benedetto Студен чай лимон 0.33л кен', 'San Benedetto Iced Tea Lemon 0.33L can', 1.07, 'assets/images/drinks/sanben-tea-lemon-330.png', 60),
  ('sanben_tea_peach', 3, 'San Benedetto Студен чай праскова 0.33л кен', 'San Benedetto Iced Tea Peach 0.33L can', 1.07, 'assets/images/drinks/sanben-tea-peach-330.png', 70),
  ('cola', 3, 'Coca-Cola 0.33л', 'Coca-Cola 0.33L', 1.07, 'assets/images/drinks/coca-cola.png', 80),
  ('cola0', 3, 'Coca-Cola Zero 0.33л', 'Coca-Cola Zero 0.33L', 1.07, 'assets/images/drinks/coca-zero.png', 90),
  ('fanta', 3, 'Fanta Портокал 0.33л', 'Fanta Orange 0.33L', 1.07, 'assets/images/drinks/fanta.png', 100),
  ('redbull', 3, 'Red Bull 0.355л', 'Red Bull 0.355L', 1.59, 'assets/images/drinks/red-bull.png', 110),
  ('panna50', 4, 'Aqua Panna 0.5л', 'Aqua Panna 0.5L', 1, 'assets/images/drinks/aqua-panna-75.png', 10),
  ('benedo_spa', 4, 'San Benedetto газирана 0.5л', 'San Benedetto sparkling 0.5L', 0.82, 'assets/images/drinks/san-benedetto-sparkling.png', 20),
  ('perrier_st', 4, 'Perrier Минерална вода 0.33л', 'Perrier Mineral Water 0.33L', 1.23, 'assets/images/drinks/perrier-still.png', 30),
  ('perrier_spa', 4, 'Perrier Газирана минерална 0.33л', 'Perrier Sparkling Mineral 0.33L', 1.64, 'assets/images/drinks/perrier-sparkling.png', 40),
  ('panna25', 4, 'Aqua Panna 0.25л', 'Aqua Panna 0.25L', 1.53, 'assets/images/drinks/aqua-panna-25.png', 50),
  ('panna75', 4, 'Aqua Panna 0.75л', 'Aqua Panna 0.75L', 2.56, 'assets/images/drinks/aqua-panna-75.png', 60),
  ('pelegrino75', 4, 'San Pellegrino газирана 0.75л', 'San Pellegrino sparkling 0.75L', 2.86, 'assets/images/drinks/san-pelegrino-75.png', 70),
  ('pelegrino', 4, 'San Pellegrino газирана 0.25л', 'San Pellegrino sparkling 0.25L', 1.53, 'assets/images/drinks/san-pelegrino.png', 80)
ON CONFLICT (id) DO NOTHING;

-- Seed: addon services (generated from reservation-catalog.js addonServices, verbatim)
INSERT INTO public.addon_services (id, name_bg, name_en, price_eur, hint_bg, hint_en, free_until, max_qty, img, sort_order) VALUES
  ('photo2', 'Фотограф за 2 часа', 'Photographer 2h', 174, NULL, NULL, NULL, NULL, 'assets/images/services/photographer.jpg', 10),
  ('photo4', 'Фотограф за 4 часа', 'Photographer 4h', 297, NULL, NULL, NULL, NULL, 'assets/images/services/photographer.jpg', 20),
  ('booth2', 'Фото будка 360° (2 часа)', '360° Photo Booth (2 hours)', 199, NULL, NULL, NULL, NULL, 'assets/images/services/svc-photobooth.jpg', 30),
  ('booth4', 'Фото будка 360° (4 часа)', '360° Photo Booth (4 hours)', 286, NULL, NULL, NULL, NULL, 'assets/images/services/svc-photobooth.jpg', 40),
  ('wall_s', 'Декоративна стена SILVER', 'Decorative wall SILVER', 182, NULL, NULL, NULL, NULL, 'assets/images/services/wall-silver.jpg', 50),
  ('wall_g', 'Декоративна стена GOLD', 'Decorative wall GOLD', 182, NULL, NULL, NULL, NULL, 'assets/images/services/wall-gold.jpg', 60),
  ('flare_s', 'Заря 150-170 сек.', 'Sparkle fountain 150-170s', 225, NULL, NULL, NULL, NULL, 'assets/images/services/fireworks.jpg', 70),
  ('flare_l', 'Заря 300-340 сек.', 'Sparkle fountain 300-340s', 404, NULL, NULL, NULL, NULL, 'assets/images/services/fireworks.jpg', 80),
  ('fountain_s', 'Светлинен фонтан 1300мм', 'Light fountain 1300mm', 49, NULL, NULL, NULL, NULL, 'assets/images/services/fountain-s.jpg', 90),
  ('fountain_l', 'Светлинен фонтан 2600мм', 'Light fountain 2600mm', 82, NULL, NULL, NULL, NULL, 'assets/images/services/fountain-l.jpg', 100),
  ('carpet_s', 'Червена пътека (6 бр.)', 'Red carpet (6 pieces)', 65, NULL, NULL, NULL, NULL, 'assets/images/services/redcarpet.jpg', 110),
  ('carpet_l', 'Червена пътека (8 бр.)', 'Red carpet (8 pieces)', 76, NULL, NULL, NULL, NULL, 'assets/images/services/redcarpet.jpg', 120),
  ('candles_h', 'Свещи в залата - 60 бр.', 'Hall candles 60 pcs', 51, NULL, NULL, NULL, NULL, 'assets/images/services/candles.jpg', 130),
  ('candles_t', 'Свещи на терасата - 50 бр.', 'Terrace candles 50 pcs', 51, NULL, NULL, NULL, NULL, 'assets/images/services/candles-terrace.jpg', 140),
  ('heater', 'Газова отоплителна гъба', 'Gas patio heater', 74, NULL, NULL, NULL, 2, 'assets/images/services/heater.jpg', 150),
  ('heater_tbl', 'Газова отоплителна маса', 'Gas heating table', 74, NULL, NULL, NULL, 1, 'assets/images/services/heater-table.jpg', 160),
  ('dj', 'DJ за 5 часа', 'DJ for 5 hours', 300, 'За всеки допълнителен час - €60', 'Each additional hour - €60', NULL, NULL, 'assets/images/services/svc-dj-new.jpg', 170),
  ('arch', 'Декоративна арка с осветление', 'Decorative arch + lights', 389, NULL, NULL, NULL, NULL, 'assets/images/services/arch.jpg', 180),
  ('decoration', 'Украса (персонализирана)', 'Decoration (custom)', 182, NULL, NULL, NULL, NULL, 'assets/images/services/svc-decoration.jpg', 190),
  ('led', 'LED екран', 'LED screen', 148, NULL, NULL, NULL, NULL, 'assets/images/services/led.jpg', 200),
  ('mic', 'Микрофони - 3бр. + брошка', 'Microphones set', 50, NULL, NULL, NULL, NULL, 'assets/images/services/mic.jpg', 210),
  ('proj', 'Мултимедия EPSON', 'EPSON multimedia projector', 92, NULL, NULL, NULL, NULL, 'assets/images/services/projector.jpg', 220),
  ('flipchart', 'Флипчарт', 'Flipchart', 25, NULL, NULL, NULL, NULL, 'assets/images/services/flipchart.jpg', 230),
  ('security', 'Охрана VTA за 6 часа', 'VTA security 6h', 100, NULL, NULL, NULL, NULL, 'assets/images/services/svc-security.jpg', 240),
  ('hygiene', 'Хигиенист за 5 часа', 'Hygienist 5h', 80, 'За всеки допълнителен час - €20', 'Each additional hour - €20', NULL, NULL, 'assets/images/services/hygienist.jpg', 250),
  ('wardrobe', 'Гардеробиер за 5 часа', 'Wardrobe attendant 5h', 90, 'За всеки допълнителен час - €20', 'Each additional hour - €20', NULL, NULL, 'assets/images/services/wardrobe.jpg', 260),
  ('valet', 'Вале-паркинг за 5 часа', 'Valet parking 5h', 141, 'За всеки допълнителен час - €25', 'Each additional hour - €25', NULL, NULL, 'assets/images/services/svc-valet.jpg', 270),
  ('cleaning', 'Почистване зала', 'Hall cleaning', 70, NULL, NULL, NULL, NULL, 'assets/images/services/cleaning.jpg', 280),
  ('numbers', 'Светещи цифри', 'Light-up numbers', 35, NULL, NULL, NULL, NULL, 'assets/images/services/glow-numbers.jpg', 290),
  ('glow_table', 'Маса светеща RGB', 'RGB glowing table', 20, NULL, NULL, NULL, 10, 'assets/images/services/table-glow.jpg', 300),
  ('bar_stool', 'Бар стол', 'Bar stool', 5, NULL, NULL, 40, NULL, 'assets/images/services/bar-stool.jpg', 310),
  ('conf_chair', 'Конферентен стол', 'Conference chair', 5, NULL, NULL, 40, NULL, 'assets/images/services/conf-chair.jpg', 320),
  ('chiavari', 'Стол „Шивари“', 'Chiavari chair', 7, NULL, NULL, 10, NULL, 'assets/images/services/chiavari.jpg', 330),
  ('cocktail_t', 'Коктейлна маса Ø70', 'Cocktail table Ø70', 13, NULL, NULL, 16, NULL, 'assets/images/services/cocktail-table.jpg', 340),
  ('rect_table', 'Правоъгълна маса 180', 'Rectangular table 180', 23, NULL, NULL, 1, NULL, 'assets/images/services/rect-table.jpg', 350),
  ('round_table', 'Кръгла маса Ø152', 'Round table Ø152', 25, NULL, NULL, 1, NULL, 'assets/images/services/round-table.jpg', 360)
ON CONFLICT (id) DO NOTHING;
